### PR TITLE
fix: lru_cache on class methods introduces leaks

### PR DESCRIPTION
**Pull request by xnought**
when 

```python
class Cheese:
    def __init__(self, animal: str):
        self.animal = animal;

    @functools.lru_cache
    def num_holes(self, weight: float):
        return Infinity
```

apparently even when the created object `swiss = Cheese("cow")` goes out of scope, the memory within swiss is not garbage collected (like animal) if num_holes was called at some point.

This is because `functools.lru_cache` looks at the parameters of numHoles, and self happens to be one of them. Somehow this leads to weirdness as described in #522.

I switched to `methodtools.lru_cache` which is the same thing, but handles for classes.

### CODE REVIEW

**Comment by cabreraalex** [comment]
What if we take it out of the Zeno object?

**Comment by xnought** [comment]
I didn't want to hash extra stuff.

the run_tsne would need the dataframe to be passed in as an argument if it were separate

**Comment by cabreraalex** [comment]
I see, so now it just hashes the model name? awesome!

**Comment by xnought** [comment]
bingo

**Pull request merged**
