### PR TITLE
feat: coloring and filtering for scatterplot view

### PR DESCRIPTION
**Pull request by xnought**
- [x] handle when there are more than 10 nominal colors (should I just do no legend and no colors?)
- [x] column `id` breaks the legend (fix this somehow)
- [x] When coloring changes, keep the selected points highlighted
- [x] clean up code

### CODE REVIEW

**Comment by cabreraalex** [comment]
I think lasso should select both filtered and non-filtered points

**Comment by xnought** [comment]
Try it out for yourself, I thought it was totally unintuitive.

**Comment by cabreraalex** [comment]
LGTM, let me know if you want to make any more changes and I'll merge

**Comment by xnought** [comment]
**Hell yes! Merge it!** 

(I'll spend time on refactoring and cleaning some stuff up on another pr later)

**Pull request merged**
